language: swift
osx_image: xcode9.2
before_script:
  - swift run -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib Vapor-Server &
script:
  - xcodebuild -project Vapor-XCTest.xcodeproj -scheme Vapor-XCTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
after_script:
  - kill $(jobs -p)
