language: objective-c
osx_image: xcode9.2
#before_script:
#  - swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib
#  - swift run Vapor-Server &
script:
  - xcodebuild test -project Vapor-XCTest.xcodeproj -scheme Vapor-XCTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#after_script:
#  - kill $(jobs -p)
