language: objective-c
osx_image: xcode9.3
before_script:
  - swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib
  - .build/x86_64-apple-macosx10.10/debug/Vapor-Server serve &
script:
  - xcodebuild test -project Vapor-XCTest.xcodeproj -scheme Vapor-XCTest -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.3' ONLY_ACTIVE_ARCH=NO | xcpretty -c
#after_script:
#  - kill $(jobs -p)
