os:
  - osx
language: swift
osx_image: xcode9.2
xcode_project: Vapor-XCTest.xcodeproj
xcode_scheme: Vapor-XCTest
before_script:
  - swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib
  - swift run
