os:
  - osx
language: swift
osx_image: xcode9.2
xcode_project: Vapor-XCTest.xcodeproj
xcode_scheme: Vapor-XCTest
before_script:
  - brew install openssl
  - brew install ctls
  - swift build
  - swift run
